"use strict";
(() => {
  const KEY="hammyOnlineV1";
  const CODE=/^[A-Z2-9]{8}$/;
  const el=id=>document.getElementById(id);
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
  const normalize=s=>String(s||"").toUpperCase().replace(/[^A-Z2-9]/g,"").slice(0,8);
  const read=()=>{try{return {apiUrl:"",visibility:"unlisted",friends:[],...JSON.parse(localStorage.getItem(KEY)||"{}")} }catch{return {apiUrl:"",visibility:"unlisted",friends:[]}}};
  const write=value=>localStorage.setItem(KEY,JSON.stringify(value));
  const base=()=>{const s=read(),configured=String(s.apiUrl||"").trim().replace(/\/+$/,"");return configured||((location.protocol==="http:"||location.protocol==="https:")?location.origin:"http://localhost:8080")};
  const api=async path=>{const r=await fetch(base()+path,{headers:{"Content-Type":"application/json"}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Server error ${r.status}`);return d};
  const status=(message,type="")=>{const box=el("onlineStatus");if(box){box.textContent=message;box.className="online-status"+(type?" "+type:"")}};
  const names={bed:"Cozy Bed",sofa:"Tiny Sofa",desk:"Study Desk",plant:"Berry Plant",aquarium:"Aquarium",tunnel:"Play Tunnel",toybox:"Toy Box",bookshelf:"Book Shelf",lamp:"Moon Lamp",rug:"Cloud Rug",wheel:"Deluxe Wheel",snack:"Snack Table",music:"Music Player",castle:"Hamster Castle",giantWheel:"Giant Wheel",bunkBed:"Bunk Bed",gamingDesk:"Gaming Desk",pool:"Indoor Pool",bubbleBath:"Bubble Bath",cinema:"Mini Cinema",musicStage:"Music Stage",capsuleBed:"Capsule Bed",treehouse:"Treehouse",aquariumTunnel:"Aquarium Tunnel",kitchenSet:"Mini Kitchen",trainSet:"Train Set",clawMachine:"Claw Machine",playground:"Playground",portal:"Magic Portal"};
  const rooms={home:"Home",bedroom:"Bedroom",kitchen:"Kitchen",bathroom:"Bathroom",study:"Study Room",music:"Music Room",game:"Game Room",garden:"Garden",rooftop:"Rooftop",aquarium:"Aquarium Room",space:"Space Room",winter:"Winter Cabin",beach:"Beach House"};
  const demos=[
   {code:"DEMO2468",nickname:"MapleHammy",visibility:"public",skinColors:{fur:"#f4c2d2",patch:"#e891ad"},costume:"Star Pajamas",premium:true,stats:{practiceDays:34,totalFocusMinutes:1280,streak:8,lootLevel:7,sessionCount:52},base:{room:"garden",wall:"#dff5e9",floor:"#d4b98d",items:[{type:"treehouse",x:24,y:49,scale:.82,rotation:-2,color:"#8c6c4b"},{type:"playground",x:70,y:68,scale:.76,rotation:1,color:"#7ab9d2"}]},updatedAt:new Date().toISOString(),demo:true},
   {code:"DEMO3579",nickname:"FocusNova",visibility:"public",skinColors:{fur:"#554086",patch:"#273d76"},costume:"Galaxy Hoodie",premium:true,stats:{practiceDays:81,totalFocusMinutes:3265,streak:19,lootLevel:14,sessionCount:128},base:{room:"space",wall:"#323655",floor:"#5d4760",items:[{type:"capsuleBed",x:25,y:54,scale:.8,rotation:-1,color:"#a7bbd8"},{type:"portal",x:77,y:49,scale:.72,rotation:0,color:"#7d64d8"}]},updatedAt:new Date().toISOString(),demo:true}
  ];
  let page=0,hasMore=true,loading=false,profiles=[];
  function avatar(p){const c=p.skinColors||{};return `<div class="online-avatar" style="--avatar-fur:${esc(c.fur||"#fff")};--avatar-patch:${esc(c.patch||"transparent")};--avatar-bg:${p.premium?"#d7c5fa":"#e7def3"}"><span class="ear left"></span><span class="ear right"></span><span class="face"></span><span class="patch"></span><span class="eye left"></span><span class="eye right"></span><span class="nose"></span></div>`}
  function baseView(p){const b=p.base||{items:[]};const items=(b.items||[]).slice(0,30).map(i=>names[i.type]?`<div class="online-base-item" style="left:${clamp(i.x,4,96)}%;top:${clamp(i.y,12,92)}%;--rotation:${clamp(i.rotation,-180,180)}deg;--scale:${clamp(i.scale,.5,1.6)};--item-color:${/^#[0-9a-f]{6}$/i.test(i.color||"")?i.color:"#a88fd5"}"><span>${esc(names[i.type])}</span></div>`:"").join("");return `<div class="online-base" style="--base-wall:${/^#[0-9a-f]{6}$/i.test(b.wall||"")?b.wall:"#eadffc"};--base-floor:${/^#[0-9a-f]{6}$/i.test(b.floor||"")?b.floor:"#dfbf91"}"><div class="online-base-window"></div>${items}<div class="online-base-hamster">${avatar(p)}</div></div>`}
  function shareUrl(code){const u=new URL(location.href);u.searchParams.set("profile",normalize(code));u.hash="";return u.toString()}
  async function share(p){const url=shareUrl(p.code),data={title:`${p.nickname}'s Hammy Focus House`,text:`Visit ${p.nickname}'s hamster stats and base.`,url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(url);status("Profile link copied.","success")}}catch(e){if(e.name!=="AbortError")status("Could not share the link.","error")}}
  function open(p){el("friendCodeInput").value=p.code;el("viewFriendCode").click()}
  function saveFriend(p){const s=read();s.friends=Array.isArray(s.friends)?s.friends:[];if(!s.friends.includes(p.code))s.friends.push(p.code);s.cachedFriends=Array.isArray(s.cachedFriends)?s.cachedFriends:[];s.cachedFriends=[...s.cachedFriends.filter(x=>x.code!==p.code),p];write(s);el("friendCodeInput").value=p.code;el("viewFriendCode").click()}
  function card(p){const s=p.stats||{},article=document.createElement("article");article.className="online-friend-card gallery-profile-card";article.dataset.galleryCode=p.code;article.innerHTML=`<div class="online-mini-profile">${avatar(p)}<div><strong>${esc(p.nickname)}</strong><p class="muted">${esc(p.costume||"No costume")}${p.premium?" · Premium":""}</p><div class="online-mini-stats"><div class="online-mini-stat"><strong>${clamp(s.practiceDays,0,999999)}</strong><span>Days</span></div><div class="online-mini-stat"><strong>${clamp(s.streak,0,999999)}</strong><span>Streak</span></div><div class="online-mini-stat"><strong>${clamp(s.lootLevel,1,999999)}</strong><span>Loot Lv.</span></div></div></div></div><div class="gallery-room-title">${esc(rooms[p.base?.room]||"Hamster Base")}</div><div class="gallery-base-peek">${baseView(p)}</div><div class="online-actions"></div>`;const a=article.querySelector(".online-actions");[["View full base","primary",()=>open(p)],["Share","secondary",()=>share(p)],["Save friend","secondary",()=>saveFriend(p)]].forEach(([t,c,f])=>{const b=document.createElement("button");b.textContent=t;b.className=c;b.addEventListener("click",f);a.appendChild(b)});return article}
  function render(){const g=el("publicGalleryGrid");if(!g)return;g.innerHTML="";if(!profiles.length){g.innerHTML='<div class="online-empty">No public profiles yet. Publish yours as Public to appear here.</div>';return}profiles.forEach(p=>g.appendChild(card(p)))}
  async function load(reset=false){if(loading||(!hasMore&&!reset))return;if(reset){page=0;hasMore=true;profiles=[];render()}loading=true;el("galleryLoading").classList.remove("hidden");try{const sort=el("gallerySort").value;const d=await api(`/api/gallery?page=${page}&limit=12&sort=${encodeURIComponent(sort)}`);const incoming=Array.isArray(d.profiles)?d.profiles:[];const seen=new Set(profiles.map(p=>p.code));incoming.forEach(p=>{if(!seen.has(p.code)){profiles.push(p);seen.add(p.code)}});page++;hasMore=Boolean(d.hasMore);render();status(`Loaded ${profiles.length} public profile${profiles.length===1?"":"s"}.`,"success")}catch(e){if(page===0){profiles=[...demos];hasMore=false;render();status("Showing demo gallery because the online server is not connected.","")}else status(e.message||"Could not load gallery.","error")}finally{loading=false;el("galleryLoading").classList.add("hidden");el("loadMoreGallery").classList.toggle("hidden",!hasMore)}}
  async function openLink(){const code=normalize(new URL(location.href).searchParams.get("profile"));if(!CODE.test(code))return;document.querySelector('[data-page="online"]')?.click();el("friendCodeInput").value=code;setTimeout(()=>el("viewFriendCode").click(),100)}
  function init(){if(!el("publicGalleryGrid"))return;const s=read();el("onlineVisibility").value=s.visibility||"unlisted";el("onlineVisibility").addEventListener("change",()=>{const x=read();x.visibility=el("onlineVisibility").value;write(x)});el("shareMyProfile").addEventListener("click",()=>{const x=read();if(x.code)share({code:x.code,nickname:x.nickname||"My Hamster"})});el("refreshGallery").addEventListener("click",()=>load(true));el("gallerySort").addEventListener("change",()=>load(true));el("loadMoreGallery").addEventListener("click",()=>load(false));const observer=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)&&hasMore)load(false)},{rootMargin:"220px"});observer.observe(el("gallerySentinel"));document.querySelector('[data-page="online"]')?.addEventListener("click",()=>{if(!profiles.length)load(true)});load(true);openLink()}
  init();
})();
